# Generated by Django 3.2.6 on 2025-02-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='pacientes',
            field=models.ManyToManyField(related_name='proyectos', to='home.DatosDemograficos', verbose_name='Pacientes'),
        ),
    ]
