# Generated by Django 3.2.6 on 2025-01-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosDemograficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PS', 'Pasaporte')], max_length=2)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)'), ('union_libre', 'Unión Libre')], max_length=20)),
                ('escolaridad', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado')], max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('eps', models.CharField(max_length=100)),
                ('lateralidad', models.CharField(choices=[('diestro', 'Diestro'), ('zurdo', 'Zurdo'), ('ambidiestro', 'Ambidiestro')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_acompanante', models.CharField(blank=True, max_length=200, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_acompanante', models.CharField(blank=True, max_length=20, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_evaluacion', models.DateField()),
                ('hora_evaluacion', models.TimeField()),
                ('evaluador', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos Demográficos',
                'verbose_name_plural': 'Datos Demográficos',
            },
        ),
    ]
