# Generated by Django 3.2.6 on 2025-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_proyecto_pacientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='nombres_apellidos',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='celular',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='correo',
            field=models.EmailField(default='sincorreo@example.com', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='correo_acompanante',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico del Acompañante'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='departamento_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento de Residencia'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='direccion_residencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de Residencia'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='municipio_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio de Residencia'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='nombre_acompanante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Acompañante'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='numero_hijos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Hijos'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País de Residencia'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='primer_apellido',
            field=models.CharField(default=' ', max_length=100, verbose_name='Primer Apellido'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='primer_nombre',
            field=models.CharField(default=' ', max_length=100, verbose_name='Primer Nombre'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='relacion_acompanante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relación con el Participante'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='rh',
            field=models.CharField(default=' ', max_length=5, verbose_name='RH'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='segundo_apellido',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='segundo_nombre',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AddField(
            model_name='datosdemograficos',
            name='telefono_acompanante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Acompañante'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='escolaridad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escolaridad'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='lateralidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lateralidad'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='numero_documento',
            field=models.CharField(default=' ', max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religión'),
        ),
    ]
