# Generated by Django 3.2.6 on 2025-01-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_datosdemograficos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='evaluador',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='fecha_evaluacion',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='hora_evaluacion',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='nombre_acompanante',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='parentesco',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='telefono_acompanante',
        ),
        migrations.RemoveField(
            model_name='datosdemograficos',
            name='ultima_actualizacion',
        ),
    ]
