# Generated by Django 3.2.6 on 2025-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250228_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdemograficos',
            name='correo',
            field=models.EmailField(default='sincorreo@example.com', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero(a)'), ('Casado', 'Casado(a)'), ('UnionLibre', 'Unión libre'), ('Viudo', 'Viudo(a)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosdemograficos',
            name='lateralidad',
            field=models.CharField(choices=[('Diestro', 'Diestro'), ('Zurdo', 'Zurdo'), ('Ambidiestro', 'Ambidiestro')], default='', max_length=20),
        ),
    ]
