# Generated by Django 3.2.6 on 2025-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250228_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdemograficos',
            name='celular',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
