# Generated by Django 3.2.6 on 2025-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_datosdemograficos_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdemograficos',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True, verbose_name='Grupo Sanguíneo'),
        ),
    ]
