# Generated by Django 3.2.6 on 2025-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_datosdemograficos_grupo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosdemograficos',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('primario', 'Primario'), ('bachiller', 'Bachiller'), ('universidad', 'Universidad'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('especializacion', 'Especialización')], max_length=20, null=True, verbose_name='Escolaridad'),
        ),
    ]
