# Generated by Django 3.2.6 on 2025-03-02 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_datosdemograficos_escolaridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitaexamen',
            name='resultado',
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.JSONField(verbose_name='Respuestas del Examen')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examenes', to='home.datosdemograficos')),
                ('visita_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='home.visitaexamen')),
            ],
            options={
                'unique_together': {('visita_examen', 'paciente')},
            },
        ),
    ]
