# Generated by Django 3.2.6 on 2025-03-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_visita_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='visita',
            name='evaluador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Visita')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='home.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='visita',
            name='Tipo_visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='home.tipovisita'),
        ),
    ]
