# Generated by Django 3.2.6 on 2025-03-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20250310_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovisita',
            name='observaciones',
        ),
    ]
