# Generated by Django 3.2.6 on 2025-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_tipovisita_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovisita',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
