# Generated by Django 3.2.6 on 2025-03-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_tipovisita_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovisita',
            name='examenes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Exámenes'),
        ),
    ]
