# Generated by Django 3.2.6 on 2025-03-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_tipovisita_examenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='home.datosdemograficos'),
        ),
    ]
