# Generated by Django 3.2.6 on 2025-03-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_visita_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoExamen',
        ),
    ]
