# Generated by Django 3.2.6 on 2025-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_resultadoexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaexamen',
            name='resultado',
            field=models.JSONField(blank=True, null=True, verbose_name='Respuestas del Examen'),
        ),
    ]
