# Generated by Django 3.2.6 on 2025-03-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_visitaexamen_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='acompanante_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Acompañante'),
        ),
        migrations.AddField(
            model_name='visita',
            name='acompanante_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Acompañante'),
        ),
        migrations.AddField(
            model_name='visita',
            name='acompanante_relacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relación con el Paciente'),
        ),
        migrations.AddField(
            model_name='visita',
            name='acompanante_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Acompañante'),
        ),
    ]
